// Generated by CIRCT firtool-1.66.0
module MuxKeyInternal(	// @[src/main/scala/mux_generator/mux_generator.scala:6:7]
  output [1:0] io_out,	// @[src/main/scala/mux_generator/mux_generator.scala:7:14]
  input  [1:0] io_key,	// @[src/main/scala/mux_generator/mux_generator.scala:7:14]
  input  [3:0] io_lut_0,	// @[src/main/scala/mux_generator/mux_generator.scala:7:14]
               io_lut_1,	// @[src/main/scala/mux_generator/mux_generator.scala:7:14]
               io_lut_2,	// @[src/main/scala/mux_generator/mux_generator.scala:7:14]
               io_lut_3	// @[src/main/scala/mux_generator/mux_generator.scala:7:14]
);

  assign io_out =
    io_key == io_lut_3[3:2]
      ? io_lut_3[1:0]
      : io_key == io_lut_2[3:2]
          ? io_lut_2[1:0]
          : io_key == io_lut_1[3:2]
              ? io_lut_1[1:0]
              : io_key == io_lut_0[3:2] ? io_lut_0[1:0] : 2'h0;	// @[src/main/scala/mux_generator/mux_generator.scala:6:7, :20:31, :21:31, :26:10, :30:{17,33}, :31:14]
endmodule

module MuxKey(	// @[src/main/scala/mux_generator/mux_generator.scala:39:7]
  output [1:0] io_out,	// @[src/main/scala/mux_generator/mux_generator.scala:40:14]
  input  [1:0] io_key,	// @[src/main/scala/mux_generator/mux_generator.scala:40:14]
  input  [3:0] io_lut_0,	// @[src/main/scala/mux_generator/mux_generator.scala:40:14]
               io_lut_1,	// @[src/main/scala/mux_generator/mux_generator.scala:40:14]
               io_lut_2,	// @[src/main/scala/mux_generator/mux_generator.scala:40:14]
               io_lut_3	// @[src/main/scala/mux_generator/mux_generator.scala:40:14]
);

  MuxKeyInternal mux (	// @[src/main/scala/mux_generator/mux_generator.scala:46:19]
    .io_out   (io_out),
    .io_key   (io_key),
    .io_lut_0 (io_lut_0),
    .io_lut_1 (io_lut_1),
    .io_lut_2 (io_lut_2),
    .io_lut_3 (io_lut_3)
  );	// @[src/main/scala/mux_generator/mux_generator.scala:46:19]
endmodule

module top(	// @[src/main/scala/top.scala:11:7]
  input        clock,	// @[src/main/scala/top.scala:11:7]
               reset,	// @[src/main/scala/top.scala:11:7]
  input  [1:0] io_a_0,	// @[src/main/scala/top.scala:12:14]
               io_a_1,	// @[src/main/scala/top.scala:12:14]
               io_a_2,	// @[src/main/scala/top.scala:12:14]
               io_a_3,	// @[src/main/scala/top.scala:12:14]
               io_s,	// @[src/main/scala/top.scala:12:14]
  output [1:0] io_y	// @[src/main/scala/top.scala:12:14]
);

  MuxKey mux (	// @[src/main/scala/top.scala:17:19]
    .io_out   (io_y),
    .io_key   (io_s),
    .io_lut_0 ({2'h0, io_a_0}),	// @[src/main/scala/top.scala:19:17]
    .io_lut_1 ({2'h1, io_a_1}),	// @[src/main/scala/top.scala:20:17]
    .io_lut_2 ({2'h2, io_a_2}),	// @[src/main/scala/top.scala:21:23]
    .io_lut_3 ({2'h3, io_a_3})	// @[src/main/scala/top.scala:22:23]
  );	// @[src/main/scala/top.scala:17:19]
endmodule

